import Main from '@/components/global/Main';

export default function LandingPage() {
  return (
    <Main>
      <h1>Welcome to Create Next App</h1>
      <p>Generated by create next app</p>
    </Main>
  );
}
